feat: add cheatcode support
matter-labs/era-revm pull request #46
Opened 2023-12-04 16:30 UTC by nbaztec

# What :computer: 
* Adds cheatcode support

# Why :hand:
* Required for foundry feature parity

# Evidence :camera:
tests pass

2023-12-04 19:50 UTC, Deniallugo requested changes

2023-12-04 19:50 UTC, Deniallugo commented on src/transactions.rs
> +use multivm::{vm_latest::VmExecutionResultAndLogs, vm_refunds_enhancement::TracerPointer};
please keep it consistent. 
It's from `VmExecutionResultAndLogs` are from interface

2023-12-04 19:50 UTC, Deniallugo commented on src/transactions.rs
> +    > = vec![Box::new(CheatcodeTracer::new())];
You can use method `into_tracer_pointer` and remove all boxes and types.

2023-12-04 20:06 UTC, Deniallugo commented on src/transactions.rs
> +        >,
You can now remove type annotations.

2023-12-05 09:24 UTC, Deniallugo commented on src/cheatcodes.rs
> +pub struct CheatcodeTracer {}
```suggestion
pub struct CheatcodeTracer;
```

2023-12-05 10:17 UTC, Deniallugo approved these changes
Good start! let's move further!

2023-12-05 11:03 UTC, MexicanAce commented on .github/workflows/tests.yaml
> +        git fetch && git checkout nish-cargo-lock-fix
(To be removed) Let's remove this `git checkout` before merge

2023-12-05 11:04 UTC, MexicanAce commented on .github/workflows/tests.yaml
> +        run: cd tests && ls -l && ls -l lib && ls -l lib/forge-std &&  ./test.sh
Let's clean this `run` command before merge 😅

2023-12-05 13:15 UTC, dutterbutter approved these changes

2023-12-05 16:10 UTC, merged